### ISSUE TITLE
Previous comments should be removed on pass

### ISSUE THREAD

**Issue by ssbarnea** [jesusvasquez333/verify-pr-label-action#17]
Once the user added the requested label, this action should removed its previous comment(s) as they are no longer valid and they spam the issue.

I would argue that it may even prove useful to have an option not to add any comment at all to avoid this. The fact that the action fails is already providing enough hints that one check failed.

**Comment by jesusvasquez333** [comment]
Thank you for your feedback @ssbarnea. I don't think previous comments should be removed once the label are added. The intention of the comment is to indicate to user, who might be unfamiliar with this action, why the check failed and what they should do to fixed. So, it tries to mimic what a human review will do.

However, I think adding an additional option to disable the comments is a good idea, and will let the user decide the behavior of the action.

**Comment by jesusvasquez333** [comment]
After reading the [GitHub API](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request) documentation (which [pygithub uses](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request)), it turns out that the `body` of the review is required. So, unfortunately there is not way of crating a review with those messages appearing in the PR history. 

Also, I didn't find any method in `pygithub` to remove previous reviews (although, if I understood correctly the GitHub API documentation, [it is supported](https://docs.github.com/en/rest/reference/pulls#delete-a-pending-review-for-a-pull-request)). I will dig more into this, but this doesn't seen to be possible either. 

But I think the proposal done in #20 will solve this issue as well, as it will add an option to disable reviews and relay on the action exit status instead.

**Comment by jesusvasquez333** [comment]
I just merged #21 which adds an option [disable-reviews](https://github.com/jesusvasquez333/verify-pr-label-action#disable-reviews) to disable the posting of reviews in the pull request and instead uses the exit code to make the check to fail or pass.

This new feature is available now in the latest version [v1.4.0](https://github.com/jesusvasquez333/verify-pr-label-action/releases/tag/v1.4.0).
