### ISSUE TITLE
Option to not mark PR as approved

### ISSUE THREAD

**Issue by Pezmc** [jesusvasquez333/verify-pr-label-action#20]
Currently, this action either marks a PR as "needs changes" or marks it as approved 

https://github.com/jesusvasquez333/verify-pr-label-action/blob/2f0319c23a61915af52e8f905cf7c272be3b363d/verify_pr_lables.py#L140-L143

Unfortunately, that means PR's often slip through the net for human review as they're already marked as approved. 

I'd like an option to disable the review features and simply exit with an error or success code, failing the check.

**Comment by jesusvasquez333** [comment]
Hi @Pezmc, thank you for your feedback. 

It is not clear to me what you mean when saying that a human review can make the check to slip through the net. The action only takes into consideration reviews done by this module (based on the review user login):
https://github.com/jesusvasquez333/verify-pr-label-action/blob/2f0319c23a61915af52e8f905cf7c272be3b363d/verify_pr_lables.py#L110-L115
https://github.com/jesusvasquez333/verify-pr-label-action/blob/2f0319c23a61915af52e8f905cf7c272be3b363d/verify_pr_lables.py#L132-L133

So, other reviews done by humans should not override the review done by this module. It will be equivalent to having two different reviews, and the fact that the approval of one user won't change the request from changes from the other user. 

Maybe you can provide an example situation where the check fails under this circumstances? 

This action was intentionally designed to avoid exiting with error codes in order to prevent the problem described in the [README file, third paragraph](https://github.com/jesusvasquez333/verify-pr-label-action/blob/master/README.md#description) and also here:
https://github.com/jesusvasquez333/verify-pr-label-action/blob/2f0319c23a61915af52e8f905cf7c272be3b363d/verify_pr_lables.py#L126-L128

**Comment by Pezmc** [comment]
Hi @jesusvasquez333,

> It is not clear to me what you mean when saying that a human review can make the check to slip through the net. The action only takes into consideration reviews done by this module (based on the review user login)

Sorry, I was unclear, I meant it's a typical pattern for us to search for our devs to search for PR's without any reviews as they're sitting waiting for code review.

Because this action is adding a github review, the PR looks like it has already been approved on first glance, so it's easy to miss that a human hasn't actually looked it over yet.

Example below, one of these PR's has **only** been approved by the GH action, the other has been reviewed by the action and a human, can you tell the difference?

<img width="971" alt="Screenshot 2021-02-18 at 10 25 26" src="https://user-images.githubusercontent.com/507155/108335900-c0b41e80-71d3-11eb-8bd2-ef0c7a111e83.png">

> This action was intentionally designed to avoid exiting with error codes in order to prevent the problem described in the README file, third paragraph and also here

I read over these docs, and I think that github has perhaps fixed this problem, I put together a [demo repo](https://github.com/Pezmc/pr-label-action-demo/pull/1) that's using my fix (https://github.com/jesusvasquez333/verify-pr-label-action/pull/21) for you.

You can see that the PR was originally marked as not ready and would block merging if configured that way:

![image](https://user-images.githubusercontent.com/507155/108336167-0bce3180-71d4-11eb-8533-fd37da375e11.png)

But as soon as I added the label, the action re-ran and the PR was marked good to merge, no other changes needed:

![image](https://user-images.githubusercontent.com/507155/108336229-1ab4e400-71d4-11eb-9123-dff738838bb4.png)

I hope that clears things up, but let me know if you have any questions! 
WIW, we've now been using a fork with this feature enabled for ~1 week without any issues.

**Comment by jesusvasquez333** [comment]
Hi @Pezmc,

Thank you very much for the clarifications and feedbacks. And thanks for the demo, that really clarified your proposal. Let me take a closer look and make sure I'm not missing anything. 

In the meanwhile, going back to your first use case example:
>Because this action is adding a github review, the PR looks like it has already been approved on first glance, so it's easy to miss that a human hasn't actually looked it over yet.
>
> Example below, one of these PR's has only been approved by the GH action, the other has been reviewed by the action and a human, can you tell the difference?

When you want to work with this action, and at the same time requiring reviews from devs, you need to configure your repo's `Require pull request reviews before merging` option to "the number of human review required + 1" (the `+1` will be the review from this action). I create [this example](https://github.com/jesusvasquez333/test-pr-labels/pull/38) for you:

In this example, I want that at least 1 dev review is required for PRs, so I set `Require pull request reviews before merging` to `2`:
![Screen Shot 2021-02-18 at 9 34 19 AM](https://user-images.githubusercontent.com/3729513/108397131-81360400-71cc-11eb-8cf3-bc0c7177eac8.png)

Then, when a PR is opened, and all the labels are correct, this action will approve it, but the PR will still required 1 more review, which should come from one of your devs:
![Screen Shot 2021-02-18 at 9 03 51 AM](https://user-images.githubusercontent.com/3729513/108396867-33b99700-71cc-11eb-80fd-30e9e3c12ba1.png)

And in the list of open PRs you will still see that that PR requires reviews:
![Screen Shot 2021-02-18 at 9 05 11 AM](https://user-images.githubusercontent.com/3729513/108396903-3ddb9580-71cc-11eb-9caf-d47bda2795da.png)

Would this configuration also solve your problem?

Thank you once again for the feedback. I will review your PR.

Jesus

**Comment by Pezmc** [comment]
Thank you for all the extra details!

We're not using the protect matching branches rules yet, but I can see how that could help fix the issue we're seeing! I will investigate further, though it _is_ less than ideal since we do occasionally merge to main without review and as a team, we generally stick with convention rather than applying rules to allow flexibility when needed.

Please do let me know if I can assist with the PR (https://github.com/jesusvasquez333/verify-pr-label-action/pull/21) review, I rebased onto master and resolved the conflicts.

**Comment by macleodmac** [comment]
First of all, thank you very much for your work on this action!

I'm also keen on this feature with the same problem in mind - we want to just rely on failed checks for validating these sorts of things rather than using the request changes / approve cycle.

@jesusvasquez333 your workaround does work, but IMO it is a workaround to a problem that can be solved with optionally disabling reviews

Very keen to see #21 merged if possible!

**Comment by jesusvasquez333** [comment]
@Pezmc Thank you very much for adding this new feature. I tested and merged your PR. This new feature is now available in the new released version [v1.4.0](https://github.com/jesusvasquez333/verify-pr-label-action/releases/tag/v1.4.0). Thanks!

**Comment by jesusvasquez333** [comment]
@macleodmac Thank you for your feedback. I merged the PR and the feature is now available in the latest version [v1.4.0](https://github.com/jesusvasquez333/verify-pr-label-action/releases/tag/v1.4.0). I hope that works better for your use case.
