### ISSUE TITLE
Stacktrace due to 403 error with incomplete info

### ISSUE THREAD

**Issue by ssbarnea** [jesusvasquez333/verify-pr-label-action#9]
When check fails it seems to produce a stacktrace like below,

![ss](https://sbarnea.com/ss/Screen-Shot-2020-07-21-10-58-21.92.png)

I mention that the screenshot includes full output, the last line being the one ending in "by", even more confusing.

I suspect this has something to do with token permissions? Still documentation does not mention anything about this.

**Comment by jesusvasquez333** [comment]
@ssbarnea Thanks for the feedback.

From the traceback, the `POST` request to create a review failed with status code `403` which I defined as `Resource not accessible by integration`. This exception came from the [GitHub python package](https://github.com/PyGithub/PyGithub/blob/v1.47/github/PullRequest.py#L485). Not sure why the output was truncated, but that would be an issue with the Github's action viewer. 

This problem seems to be related to this issue: https://github.com/actions/first-interaction/issues/10

Are you by any change working on a fork? Can you point me to the PR where this error happened?

**Comment by vboulineau** [comment]
We also experienced that with this PR:
https://github.com/DataDog/datadog-operator/pull/154

The source branch comes from a fork, we do not see such issues with PRs coming from same repo.

**Comment by jesusvasquez333** [comment]
@ssbarnea, @vboulineau The problem is related to permission of the Github action when running on a fork. When the action runs on a fork, it run with read-only permissions, so it not able to create a pull request review, and it fails with the error message you posted above.

In order to help fixing this problem, [Github added a new trigger event](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)  `pull_request_target` which behaves like the `pull_request` event, but runs in the base of the pull request, and therefore will have write permissions. The problem with using this new event is that, the pull request number is not longer available in the environmental variables, so it needs to be passed as a new input to the action (fortunately this number is available in the GitHub context). 

I added support for this new feature in version `v1.3.1`. In order to use you just need to:
1. Update the version you are using to `v1.3.1`.
2. Change the trigger from `pull_request` to `pull_request_target`.
3. Add this new input value: `pull-request-number: '${{ github.event.pull_request.number }}'`.

I added an [example](https://github.com/jesusvasquez333/verify-pr-label-action/blob/master/README.md#if-you-want-to-allow-prs-from-forks) in the documentation.

With this changes all PR will work, including those coming from forks.
